#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ladderMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     backRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    rakeServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    pendulumMoverServo,   tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  mtr_S1_C1_3,     bottom,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define COMPETITION

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drive.h"
#include "drive.c"
#include "ladder.h"
#include "ladder.c"
#include "flag.h"
#include "flag.c"
#include "rake.h"
#include "rake.c"
#include "drivers/hitechnic-irseeker-v2.h"

DriveSys drive;
LadderSys ladder;
FlagSys flag;
RakeSys rake;

void initializeRobot()
{
	        drive.backLeft = backLeft;
        drive.backRight = backRight;
        drive.frontLeft = frontLeft;
        drive.frontRight = frontRight;

        ladder.ladderMotor = ladderMotor;

        flag.flagMotor = flagMotor;

        rake.rakeServo = rakeServo;
        rake.maxValue = 210;
        rake.minValue = 120;

        rake.pendulumMoverServo = pendulumMoverServo;

		servo[rake.rakeServo] = 135;
		servo[rake.pendulumMoverServo] = 0;

		return;
}

int maxSig(int num0, int num1, int num2, int num3, int num4){
    if(num0>num1 && num0>num2 && num0>num3 && num0>num4) return num0;
    if(num1>num2 && num1>num3 && num1>num4) return num1;
    if(num2>num3 && num2>num4) return num2;
    if(num3>num4) return num3;
    return num4;
}

void driveEncoders(int inches){
	int encoderValue = inches * -122;
	if(encoderValue>0){
		while(nMotorEncoder[frontRight]>=0){
			motor[frontRight]=-25;
			motor[frontLeft]=-25;
			motor[backRight]=-25;
			motor[backLeft]=-25;
		}
	} else if(encoderValue<0){
		while(nMotorEncoder[frontRight]<=0){
			motor[frontRight]=25;
			motor[frontLeft]=25;
			motor[backRight]=25;
			motor[backLeft]=25;
		}
	}
}

void turnRight(){
	nMotorEncoder[frontRight] = 50;
	while(nMotorEncoder[frontRight]>=0){
		motor[frontRight]=-25;
		motor[frontLeft]=-25;
		motor[backRight]=25;
		motor[backLeft]=25;
	}
}

void turnLeft(){
	nMotorEncoder[frontRight] = 50;
	while(nMotorEncoder[frontRight]<=0){
		motor[frontRight]=25;
		motor[frontLeft]=25;
		motor[backRight]=25;
		motor[backLeft]=25;
	}
}

task main(){

	initializeRobot();

	#ifdef COMPETITION
	waitForStart();   // wait for start of tele-op phase
	#endif

	PlaySound(soundBeepBeep);
	driveEncoders(10);

    //Detect IR Beacon method

	/*
	int irs[5]; //infra-red sensor strengths, maximmum signal
    HTIRS2readAllACStrength(IRSensor, irs[0], irs[1], irs[2], irs[3], irs[4]);

	while(maxSig(irs[0], irs[1], irs[2], irs[3], irs[4])!=irs[0]){
		//while IR Sensor is not detected
		//drive forward
		updateDriveSys(drive, 100, 100, 100, 100);
	}
	*/

	/*
	//drive forward
	driveEncoders(10);
	//turn and place block in basket
	turnLeft();
	driveEncoders(20); //drive into basket
	turnRight();
	driveEncoders(100); //drive to ramp
	turnLeft();
	driveEncoders(50);
	turnLeft();
	driveEncoders(150); //drive onto ramp
	*/

    //Drive backwards onto ramp method
    /*
    updateDriveSys(drive, -100, -100, -100, -100);
    wait1Msec(3000);
    */
}
